language: node_js
node_js:
- node
before_install:
- npm install -g mocha
env:
  global:
  - PORT=8080
  - HOST=enzomallard.fr
cache:
  directories:
  - node_modules
install:
- npm install
script:
- mocha --exit 2> /dev/null
notifications:
  slack:
    secure: OyBkQOLRRKRXHgcX9/SGz75HnWeOObv5pmG7uDlVSYIsySS8nd+Ug49iIHbMY6jnmYwf0jwskTqvcW+nrx6Il4Nuc4xOfTOIyJO48S0c1Mypz4UYZTY+M4hmEyPJPlrsCBZw/Wkq4zAMpRAoxh4cJlnG9qisHpd9B1q1OGU1QyDZ1JhdFBQhutGDaNN9MQ3in+sKUL85cJb+SDOTPwwwHwb6l16XkmZYdyAzBlktKNtkFz+mE2DHg26CX2qr0ZDCrE5zSF7JMPR9g4vzuxOop7tQKZCJNlA2xBru5blH7qYXi4oJNolnM93fR7VJWX+fKEFSySx/jCo12/gF1FWRwgnkD5nmX5WSFvcxUctKOXWjDRjqcbRazApNtOSto5XMU8JWkekufz0uXYIihSE9rfcBxbB4+ZLsoyFO+MsaiQEnlKWM3ZW07GQDCKbGQuTrzn0gppTXBxkft6kRRH1WjNpKxB65WBa5FiUf1K+uzY4un1XN+39xY0DM2v0uGc0412dZ96wvywaWIpu3vIykNuwY13aTPakDUmVjKyXzu8rEVbGIYWV8ICIpznSbNY8b3Y06+BHvyXrDDD5+YngzZoxiahYLqfe1TFd2mCImbOvMf4Pt8tGfVq68Xv1VcQXQ140roNcWLkEZyM5aL0jvrBMewBJ+N/4e6T0RGZOeM6w=
before_deploy: zip -r ~/build/build_$TRAVIS_BUILD_NUMBER.zip ~/build/EnzDev/CIChat
  -x \ \*node_modules/**\* \ \*.git/**\* \ \*.gitignore \ \*.deployarti.sh
deploy:
  matrix:
  - provider: script
    script: bash deployarti.sh
    on:
      branch: develop
  - provider: releases
      api_key:
    secure: gox0SX50NBRCYfbscfNZ8b5yJxVcj9T7q5wnWEPDvMe+6eZHTEr0UzbqK/9qvY5V44wB8sTgtDxqfEK5Nc0QgwAT2W72PWFj0m8I+Hq4dwAaUMgStgyrx7rEbSJiqc29rgDh9HeBU7yGN9oYbOQUUTfhjKSrrk59oHjnRMxe6liOG3EMHCCcJnfcwrU6VPd/0tngGdnJ6R6u4ZmIdiatTc4shmtFZk4eTszbJ3fcsojLCvdCAStoCbhmUYFAySQqs/LhGc7nBJckOrM1RufR1dKuK32Hm4UScHxEOV9eoaUKHX5qzR797OqUC8gSfUyyn5Iyx3ol1CM3k/61dDsEMwGBtTcg9CrVxnssfACX74WZ8xFh9kBYS+IuhWVr+PHxX9MxtkmQwJ5KKiLQ4C1CWqqFzycRhyWquyIgiJ3HS5NP05s3PiKRpIaQtUmY6+XFR0GNa/IF3+fOsd9j0fxGw2X+6rxlVQqPWCCLojQv5QV51JBOVkkm/Xb9rlNjQLWumEx9PWnvs1w5U2HkGEYU1WVoJvHB7Dbob1pU93xdslukdoDhwomTttowGIsxAGfWHNpea0RujN93LfRHGO+DjftXvQV3R8BWv8mUohZwaVBmMVhXymHWzpONU6kiZoZOuwsp0mlkN8Mlx0rdfCvqg50IQ1q5a6pdr3wXnsXrGHk=
    file: ~/build/build_$TRAVIS_BUILD_NUMBER.zip
    on:
      branch: master
